steps:
  # Node.jsのインストールと依存関係の解決
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # テストの実行
  - name: 'node:20'
    entrypoint: npm
    args: ['test']

  # ビルド
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Cloud Functionsへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - functions
      - deploy
      - x-bot
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=.
      - --entry-point=honoFunction
      - --trigger-http
      - --memory=128MB
      - --min-instances=0
      - --max-instances=1
      - --timeout=30s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-northeast1
  _FUNCTION_NAME: x-bot

timeout: 1800s 