steps:
  # Cloud Native Buildpacksを使用してコンテナイメージをビルドです。
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - build
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
      - --builder=gcr.io/buildpacks/builder:latest
      - --path=.
      - --env=NODE_ENV=production
      - --env=PORT=8080
      - --env=BP_NODE_RUN_SCRIPTS=build
      - --env=BP_NODE_VERSION=20.x
      - --verbose
      - --trust-builder

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --memory=128Mi
      - --min-instances=0
      - --max-instances=1
      - --port=8080
      - --allow-unauthenticated

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: x-bot-images
  _SERVICE_NAME: x-bot

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s