steps:
  # Node.jsのインストールと依存関係の解決
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # テストの実行
  - name: 'node:20'
    entrypoint: npm
    args: ['test']

  # ビルド
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}',
      '.'
    ]

  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    ]

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --memory=128Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=1
      - --port=8080
      - --allow-unauthenticated

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: x-bot-images
  _SERVICE_NAME: x-bot

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s